# name: airwave-airtime
services:
  
 backend: 
  build:
    context: ./backend
    # include the image 
    dockerfile: Dockerfile
  container_name: paylink_api
  # inject env variable into a container without baking them into the image which is not safe
  env_file:
     - backend/.env
     - backend/.env.development
     - backend/.env.production

  depends_on:
     - db 
     - redis 
    

  ports:
    - 8000:8000
  networks:
    - app-net
  # restart: true
  
 db:
    image: postgres:15
    restart: always
    container_name: postgres_db
    env_file:
      - backend/.env.development
    environment:
          - POSTGRES_USER=paylink_admin
          - POSTGRES_PASSWORD=paylink@2026
          - POSTGRES_DB=paylink
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paylink_admin -d paylink"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
       - 5432:5432
    volumes:
       - postgres_data:/var/lib/postgresql/data
    networks: 
       - app-net
 redis:
   image: redis:8.2.2-alpine
   container_name: redis_server
   # restart: always
   ports:
      - 6379:6379
   volumes:
      - ./data/redis:/data
   networks:
      - app-net
   command: ["redis-server", "--appendonly", "yes"]

 frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paylink_web
    env_file:
      - frontend/.env.development
      - frontend/.env.production
    ports:
       - 5173:80
    networks:
       - app-net


volumes:
  postgres_data: {}
networks:
   app-net:
     driver: bridge
        
         