import clsx, { type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { format, formatDistanceToNow } from "date-fns";

export const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));

export const fmtKES = (n: number) =>
  `KES ${Number(n).toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export const fmtKESShort = (n: number) =>
  `KES ${Number(n).toLocaleString("en-KE", { maximumFractionDigits: 0 })}`;

export const fmtDate = (d: string | Date) =>
  d ? format(new Date(d), "d MMM yyyy") : "—";

export const fmtDateTime = (d: Date) =>
  d ? format(new Date(d), "d MMM yyyy, h:mm a") : "—";

export const fmtRelative = (d: Date) =>
  d ? formatDistanceToNow(new Date(d), { addSuffix: true }) : "—";

export const fmtPhone = (p: string) => {
  if (!p) return "—";
  const s = String(p);
  if (s.startsWith("254") && s.length === 12)
    return `+254 ${s.slice(3, 6)} ${s.slice(6, 9)} ${s.slice(9)}`;
  return s;
};

export const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const el = document.createElement("textarea");
    el.value = text;
    document.body.appendChild(el);
    el.select();
    document.execCommand("copy");
    document.body.removeChild(el);
    return true;
  }
};

export const generateReceiptPDF = (transaction: any, paymentLink: any) =>
  import("jspdf").then(({ jsPDF }) => {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const W = doc.internal.pageSize.getWidth();
    const H = doc.internal.pageSize.getHeight();

    doc.setFillColor(10, 34, 20);
    doc.rect(0, 0, W, 88, "F");
    doc.setFillColor(0, 166, 81);
    doc.rect(0, 88, W, 3, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(255, 255, 255);
    doc.text("PESALINK", 40, 46);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(160, 220, 180);
    doc.text("M-Pesa Payment Receipt", 40, 64);
    doc.setFontSize(9);
    doc.setTextColor(100, 160, 120);
    doc.text("Powered by Safaricom Daraja API", 40, 78);

    doc.setFillColor(0, 166, 81);
    doc.roundedRect(W - 92, 28, 62, 26, 4, 4, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.text("PAID", W - 61, 45, { align: "center" });

    doc.setFillColor(240, 250, 244);
    doc.rect(0, 91, W, 88, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(38);
    doc.setTextColor(0, 100, 50);
    doc.text(fmtKES(transaction.amount), W / 2, 145, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(100, 140, 110);
    doc.text("Amount Received — Transaction Confirmed", W / 2, 166, {
      align: "center",
    });

    const rows = [
      ["Transaction ID", transaction.reference],
      ["M-Pesa Receipt", transaction.mpesa_receipt || "—"],
      ["Business", paymentLink?.business_name || "—"],
      ["Service", paymentLink?.description || "—"],
      ["Client", paymentLink?.client_name || "—"],
      ["M-Pesa Number", fmtPhone(transaction.phone)],
      ["Checkout ID", transaction.checkout_request_id || "—"],
      ["Date", fmtDateTime(transaction.completed_at || transaction.created_at)],
      ["Payment Method", "M-Pesa STK Push"],
      ["Status", "CONFIRMED ✓"],
    ];

    let y = 220;
    rows.forEach(([label, val], i) => {
      if (i % 2 === 0) {
        doc.setFillColor(248, 250, 248);
        doc.rect(40, y - 14, W - 80, 24, "F");
      }
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 100, 100);
      doc.text(label, 56, y);
      doc.setFont("helvetica", label === "Status" ? "bold" : "normal");
      doc.setTextColor(
        label === "Status" ? 0 : 20,
        label === "Status" ? 130 : 20,
        label === "Status" ? 60 : 20,
      );
      doc.text(String(val).slice(0, 52), W - 56, y, { align: "right" });
      y += 26;
    });

    const fy = H - 48;
    doc.setDrawColor(220, 220, 215);
    doc.line(40, fy, W - 40, fy);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(160, 160, 160);
    doc.text(
      "This receipt was auto-generated by PesaLink. Keep it as proof of payment.",
      W / 2,
      fy + 16,
      { align: "center" },
    );
    doc.text(
      "PesaLink © 2025 · Built on Safaricom Daraja API",
      W / 2,
      fy + 30,
      { align: "center" },
    );

    doc.save(`PesaLink_Receipt_${transaction.reference}.pdf`);
  });
